import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header"
import "./globals.css";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/providers/auth";
import { StoreProvider } from "@/providers/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prayog - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AuthProvider>
            <Toaster
              position="top-center"
              reverseOrder={false}
            />
            <Header />
            {children}
            <Footer />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>

  );
}
